services:
  plantuml:
    image: 'plantuml/plantuml-server:tomcat'
    ports:
      - "8080:8080"
  mkdocs:
    build: .
    links:
      - plantuml
    depends_on:
      - plantuml
    ports:
      - "8000:8000"
    environment: 
      LOCAL_BRANCH: ${LOCAL_BRANCH}
